// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QL_Nuoc;

#nullable disable

namespace QL_Nuoc.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QL_Nuoc.Models.ChiTietDonHangEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreateTimes")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreateUser")
                        .HasColumnType("datetime2");

                    b.Property<string>("DonHangID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("GiaTien")
                        .HasColumnType("real");

                    b.Property<DateTime>("LastUpdateTimes")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdateUser")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaNuocUong")
                        .HasColumnType("int");

                    b.Property<string>("NuocUongID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DonHangID");

                    b.HasIndex("NuocUongID");

                    b.ToTable("ChiTietDonHang");
                });

            modelBuilder.Entity("QL_Nuoc.Models.DonHangEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreateTimes")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreateUser")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustumerID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("LastUpdateTimes")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdateUser")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayGiao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustumerID");

                    b.ToTable("DonHang");
                });

            modelBuilder.Entity("QL_Nuoc.Models.KhachHangEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreateTimes")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreateUser")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdateTimes")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdateUser")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("QL_Nuoc.Models.LoaiNuocUongEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreateTimes")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreateUser")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdateTimes")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdateUser")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenLoaiNU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LoaiNuocUong");
                });

            modelBuilder.Entity("QL_Nuoc.Models.NuocUongEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreateTimes")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreateUser")
                        .HasColumnType("datetime2");

                    b.Property<float>("GiaTien")
                        .HasColumnType("real");

                    b.Property<DateTime>("LastUpdateTimes")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdateUser")
                        .HasColumnType("datetime2");

                    b.Property<string>("LoaiNuocUongID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenNuocUong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LoaiNuocUongID");

                    b.ToTable("NuocUong");
                });

            modelBuilder.Entity("QL_Nuoc.Models.ChiTietDonHangEntity", b =>
                {
                    b.HasOne("QL_Nuoc.Models.DonHangEntity", "DonHang")
                        .WithMany("ChiTietDonHang")
                        .HasForeignKey("DonHangID");

                    b.HasOne("QL_Nuoc.Models.NuocUongEntity", "NuocUong")
                        .WithMany("ChiTietDonHang")
                        .HasForeignKey("NuocUongID");

                    b.Navigation("DonHang");

                    b.Navigation("NuocUong");
                });

            modelBuilder.Entity("QL_Nuoc.Models.DonHangEntity", b =>
                {
                    b.HasOne("QL_Nuoc.Models.KhachHangEntity", "KhachHang")
                        .WithMany("DonHang")
                        .HasForeignKey("CustumerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("QL_Nuoc.Models.NuocUongEntity", b =>
                {
                    b.HasOne("QL_Nuoc.Models.LoaiNuocUongEntity", "LoaiNuocUong")
                        .WithMany("NuocUong")
                        .HasForeignKey("LoaiNuocUongID");

                    b.Navigation("LoaiNuocUong");
                });

            modelBuilder.Entity("QL_Nuoc.Models.DonHangEntity", b =>
                {
                    b.Navigation("ChiTietDonHang");
                });

            modelBuilder.Entity("QL_Nuoc.Models.KhachHangEntity", b =>
                {
                    b.Navigation("DonHang");
                });

            modelBuilder.Entity("QL_Nuoc.Models.LoaiNuocUongEntity", b =>
                {
                    b.Navigation("NuocUong");
                });

            modelBuilder.Entity("QL_Nuoc.Models.NuocUongEntity", b =>
                {
                    b.Navigation("ChiTietDonHang");
                });
#pragma warning restore 612, 618
        }
    }
}
